name: CI

on: [push]

jobs:
  sast-scan:
    name: Run Bandit Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Scan
        run: bandit -ll -ii -r . -f json -o bandit-report.json

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: bandit-findings
          path: bandit-report.json

  
  image_scan:
    name: Build an image and run scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
        
      - name: Log in to Docker Hub
        run: echo "${{ secrets.REPO_PASSWORD }}" | docker login -u "${{ secrets.REPO_USER }}" --password-stdin

      - name: Build and push image
        run: |
          docker build -t ${{ secrets.REPO_USER }}/myapp:latest .
          docker push ${{ secrets.REPO_USER }}/myapp:latest

      # - name: Build docker image
      #   run: docker build -t myapp:latest .

      - name: Docker Scout Scan
        uses: docker/scout-action@v1.0.9
        with:
          image: ${{secrets.REPO_USER}}/myapp:latest
          dockerhub-user: ${{ secrets.REPO_USER }}
          dockerhub-password: ${{ secrets.REPO_PASSWORD }}
          command: quickview,cves

      # - name: Docker Scout scan
      #   run:  |
      #      curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
      #      sh install-scout.sh

      #      echo ${{secrets.REPO_PASSWORD}} | docker login -u ${{secrets.REPO_USER}} --password-stdin
           
      #      docker scout quickview
      #      docker scout cves
           

        
